
//UNSTABLE API/NUMBER

#define IOC_GPIODEV_MAGIC  'B'
#define MOTOR_PWM_ON	_IO(IOC_GPIODEV_MAGIC, 10)
#define MOTOR_PWM_OFF	_IO(IOC_GPIODEV_MAGIC, 11)
#define MOTOR_ENABLE	_IO(IOC_GPIODEV_MAGIC, 13)
#define MOTOR_DIR	_IO(IOC_GPIODEV_MAGIC, 12)
#define MOTOR_LOWPWR	_IO(IOC_GPIODEV_MAGIC, 15)
#define MOTOR_STEPS_RESET	_IO(IOC_GPIODEV_MAGIC, 16)
#define MOTOR_STEPS_MAX		_IO(IOC_GPIODEV_MAGIC, 17)
#define MOTOR_STEPS_ENABLE	_IO(IOC_GPIODEV_MAGIC, 18)
